/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import static java.lang.System.exit;
import java.util.logging.Logger;
import static java.util.logging.Logger.getLogger;
import static javax.swing.UIManager.getInstalledLookAndFeels;
import static javax.swing.UIManager.setLookAndFeel;

/**
 *
 * @author INFOLUCK
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form LoginN
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_Login = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        buttonLimpar = new javax.swing.JButton();
        buttonEntrar = new javax.swing.JButton();
        buttonSair = new javax.swing.JButton();
        label_SENHA_USU = new javax.swing.JLabel();
        label_EMAIL_USU = new javax.swing.JLabel();
        label_iconkey = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Papelaria Papelândia - Login de Acesso");
        setResizable(false);

        Painel_Login.setBackground(new java.awt.Color(255, 255, 255));
        Painel_Login.setPreferredSize(new java.awt.Dimension(450, 370));

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/Login.png"))); // NOI18N

        buttonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconclean.png"))); // NOI18N
        buttonLimpar.setText("Limpar");
        buttonLimpar.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });

        buttonEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconsucess.png"))); // NOI18N
        buttonEntrar.setText("Entrar");
        buttonEntrar.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEntrarActionPerformed(evt);
            }
        });

        buttonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconexit.png"))); // NOI18N
        buttonSair.setText("Sair");
        buttonSair.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });

        LOGIN_USU.setPreferredSize(new java.awt.Dimension(120, 30));

        SENHA_USU.setPreferredSize(new java.awt.Dimension(120, 30));

        label_SENHA_USU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_SENHA_USU.setText("Senha");
        label_SENHA_USU.setPreferredSize(new java.awt.Dimension(120, 30));

        label_EMAIL_USU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_EMAIL_USU.setText("Login");
        label_EMAIL_USU.setPreferredSize(new java.awt.Dimension(120, 30));

        label_iconkey.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_iconkey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconkey.png"))); // NOI18N

        javax.swing.GroupLayout Painel_LoginLayout = new javax.swing.GroupLayout(Painel_Login);
        Painel_Login.setLayout(Painel_LoginLayout);
        Painel_LoginLayout.setHorizontalGroup(
            Painel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Painel_LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_LoginLayout.createSequentialGroup()
                        .addComponent(buttonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(buttonSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Painel_LoginLayout.createSequentialGroup()
                        .addGroup(Painel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_EMAIL_USU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LOGIN_USU, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Painel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_SENHA_USU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_LoginLayout.createSequentialGroup()
                                .addComponent(label_iconkey)
                                .addGap(49, 49, 49)
                                .addComponent(SENHA_USU, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        Painel_LoginLayout.setVerticalGroup(
            Painel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_LoginLayout.createSequentialGroup()
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Painel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_EMAIL_USU, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(label_SENHA_USU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Painel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LOGIN_USU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SENHA_USU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_iconkey))
                .addGap(18, 18, 18)
                .addGroup(Painel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
    controller.LoginDAO loginDAO = new controller.LoginDAO();
    loginDAO.clean(this);
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void buttonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEntrarActionPerformed
    controller.LoginDAO loginDAO = new controller.LoginDAO();
    model.Login mLogin = new model.Login();
    loginDAO.logar(this, mLogin);
    }//GEN-LAST:event_buttonEntrarActionPerformed

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
    exit(0);
    }//GEN-LAST:event_buttonSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
            new Login().setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public final javax.swing.JTextField LOGIN_USU = new javax.swing.JTextField();
    private javax.swing.JPanel Painel_Login;
    public final javax.swing.JPasswordField SENHA_USU = new javax.swing.JPasswordField();
    private javax.swing.JButton buttonEntrar;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton buttonSair;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel label_EMAIL_USU;
    private javax.swing.JLabel label_SENHA_USU;
    private javax.swing.JLabel label_iconkey;
    // End of variables declaration//GEN-END:variables
    private static final Logger LOG = getLogger(Login.class.getName());
}