/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.util.logging.Logger;
import static java.util.logging.Logger.getLogger;
import static javax.swing.UIManager.getInstalledLookAndFeels;
import static javax.swing.UIManager.setLookAndFeel;

/**
 *
 * @author INFOLUCK
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalN
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_MenuPrincipal = new javax.swing.JPanel();
        label_MenuPrincipal = new javax.swing.JLabel();
        buttonModuloCliente = new javax.swing.JButton();
        buttonModuloAdministrativo = new javax.swing.JButton();
        buttonSair = new javax.swing.JButton();
        buttonModuloVendedor = new javax.swing.JButton();
        labelRodape = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Papelaria Papelândia - Menu Principal");

        Painel_MenuPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        label_MenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/MenuPrincipal.png"))); // NOI18N

        buttonModuloCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconcliente.png"))); // NOI18N
        buttonModuloCliente.setText("<html><center>Módulo<br>Cliente</center></html>");
        buttonModuloCliente.setPreferredSize(new java.awt.Dimension(150, 90));
        buttonModuloCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModuloClienteActionPerformed(evt);
            }
        });

        buttonModuloAdministrativo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconadmin.png"))); // NOI18N
        buttonModuloAdministrativo.setText("<html><center>Módulo<br>Administrativo</center></html>");
        buttonModuloAdministrativo.setPreferredSize(new java.awt.Dimension(150, 90));
        buttonModuloAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModuloAdministrativoActionPerformed(evt);
            }
        });

        buttonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconexit.png"))); // NOI18N
        buttonSair.setText("<html><center>Sair</center></html>");
        buttonSair.setPreferredSize(new java.awt.Dimension(150, 90));
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });

        buttonModuloVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconvend.png"))); // NOI18N
        buttonModuloVendedor.setText("<html><center>Módulo<br>Vendedor</center></html>");
        buttonModuloVendedor.setPreferredSize(new java.awt.Dimension(150, 90));
        buttonModuloVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModuloVendedorActionPerformed(evt);
            }
        });

        labelRodape.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRodape.setText("Todos os direitos reservados a InfoLuck Tecnologia Ltda.");

        javax.swing.GroupLayout Painel_MenuPrincipalLayout = new javax.swing.GroupLayout(Painel_MenuPrincipal);
        Painel_MenuPrincipal.setLayout(Painel_MenuPrincipalLayout);
        Painel_MenuPrincipalLayout.setHorizontalGroup(
            Painel_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_MenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelRodape, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_MenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Painel_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(Painel_MenuPrincipalLayout.createSequentialGroup()
                        .addComponent(buttonModuloCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186)
                        .addComponent(buttonModuloVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonModuloAdministrativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(206, 206, 206))
        );

        Painel_MenuPrincipalLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonModuloAdministrativo, buttonModuloCliente, buttonModuloVendedor, buttonSair});

        Painel_MenuPrincipalLayout.setVerticalGroup(
            Painel_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_MenuPrincipalLayout.createSequentialGroup()
                .addComponent(label_MenuPrincipal)
                .addGap(83, 83, 83)
                .addGroup(Painel_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(buttonModuloVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonModuloCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Painel_MenuPrincipalLayout.createSequentialGroup()
                        .addComponent(buttonModuloAdministrativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(labelRodape))
        );

        Painel_MenuPrincipalLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonModuloAdministrativo, buttonModuloCliente, buttonModuloVendedor, buttonSair});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_MenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_MenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonModuloClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModuloClienteActionPerformed
        view.ModuloCliente vModuloCliente = new view.ModuloCliente();
        vModuloCliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonModuloClienteActionPerformed

    private void buttonModuloAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModuloAdministrativoActionPerformed
        view.ModuloAdministrativo vModuloAdministrativo = new view.ModuloAdministrativo();
        vModuloAdministrativo.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonModuloAdministrativoActionPerformed

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        view.Login vLogin = new view.Login();
        vLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonSairActionPerformed

    private void buttonModuloVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModuloVendedorActionPerformed
        view.ModuloVendedor vModuloVendedor = new view.ModuloVendedor();
        vModuloVendedor.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonModuloVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
            new MenuPrincipal().setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel_MenuPrincipal;
    private javax.swing.JButton buttonModuloAdministrativo;
    private javax.swing.JButton buttonModuloCliente;
    private javax.swing.JButton buttonModuloVendedor;
    private javax.swing.JButton buttonSair;
    private javax.swing.JLabel labelRodape;
    private javax.swing.JLabel label_MenuPrincipal;
    // End of variables declaration//GEN-END:variables
    private static final Logger LOG = getLogger(MenuPrincipal.class.getName());
}
