package view;


import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import static javax.swing.UIManager.getInstalledLookAndFeels;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import static java.util.logging.Logger.getLogger;
import static javax.swing.UIManager.setLookAndFeel;


/**
 *
 * @author INFOLUCK
 */
public class ModuloAdministrativo extends javax.swing.JFrame {

    /**
     * Creates new form cliente
     */
    public ModuloAdministrativo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelModuloAdministrativo = new javax.swing.JPanel();
        imgModuloAdministrativo = new javax.swing.JLabel();
        buttonHelp_Administrativo = new javax.swing.JButton();
        buttonVoltar_Administrativo = new javax.swing.JButton();
        TabelaPaineis_ModuloAdministrativo = new javax.swing.JTabbedPane();
        painelFornecedor = new javax.swing.JPanel();
        label_NOME_FOR = new javax.swing.JLabel();
        NOME_FOR = new javax.swing.JTextField();
        label_CNPJ_FOR = new javax.swing.JLabel();
        CNPJ_FOR = new javax.swing.JTextField();
        try{
            MaskFormatter CNPJ = new
            MaskFormatter("##.###.###/####-##");
            CNPJ_FOR = new JFormattedTextField(CNPJ);
        }
        catch(Exception e){

        }
        BAI_FOR = new javax.swing.JTextField();
        label_END_FOR = new javax.swing.JLabel();
        label_CID_FOR = new javax.swing.JLabel();
        CID_FOR = new javax.swing.JTextField();
        label_UF_FOR = new javax.swing.JLabel();
        label_DDDTEL_FOR = new javax.swing.JLabel();
        DDDTEL_FOR = new javax.swing.JTextField();
        try{
            MaskFormatter DDD = new
            MaskFormatter("##");
            DDDTEL_FOR = new JFormattedTextField(DDD);
        }
        catch(Exception e){

        }
        label_TEL_FOR = new javax.swing.JLabel();
        TEL_FOR = new javax.swing.JTextField();
        try{
            MaskFormatter Telefone = new
            MaskFormatter("####-####");
            TEL_FOR = new JFormattedTextField(Telefone);
        }
        catch(Exception e){

        }
        label_EMAIL_FOR = new javax.swing.JLabel();
        EMAIL_FOR = new javax.swing.JTextField();
        buttonLimpar_Fornecedor = new javax.swing.JButton();
        UF_FOR = new javax.swing.JComboBox();
        END_FOR = new javax.swing.JTextField();
        label_BAI_FOR = new javax.swing.JLabel();
        label_CEP_FOR = new javax.swing.JLabel();
        CEP_FOR = new javax.swing.JTextField();
        try{
            MaskFormatter CEP = new
            MaskFormatter("#####-###");
            CEP_FOR = new JFormattedTextField(CEP);
        }
        catch(Exception e){

        }
        buttonAdicionar_Fornecedor = new javax.swing.JButton();
        buttonExcluir_Fornecedor = new javax.swing.JButton();
        buttonAlterar_Fornecedor = new javax.swing.JButton();
        buttonPesquisar_Tabela_Fornecedor = new javax.swing.JButton();
        label_NUMEND_FOR = new javax.swing.JLabel();
        NUMEND_FOR = new javax.swing.JTextField();
        try{
            MaskFormatter DDD = new
            MaskFormatter("##");
            DDDTEL_FOR = new JFormattedTextField(DDD);
        }
        catch(Exception e){

        }
        label_COMPEND_FOR = new javax.swing.JLabel();
        COMPEND_FOR = new javax.swing.JTextField();
        try{
            MaskFormatter DDD = new
            MaskFormatter("##");
            DDDTEL_FOR = new JFormattedTextField(DDD);
        }
        catch(Exception e){

        }
        label_STATUS_FOR = new javax.swing.JLabel();
        STATUS_FOR = new javax.swing.JComboBox();
        ScrollPane_Fornecedor = new javax.swing.JScrollPane();
        tableFornecedor = new javax.swing.JTable();
        painelCategoria = new javax.swing.JPanel();
        label_DES_CAT = new javax.swing.JLabel();
        DES_CAT = new javax.swing.JTextField();
        buttonLimpar_Categoria = new javax.swing.JButton();
        ScrollPane_Categoria = new javax.swing.JScrollPane();
        tableCategoria = new javax.swing.JTable();
        buttonAdicionar_Categoria = new javax.swing.JButton();
        buttonExcluir_Categoria = new javax.swing.JButton();
        buttonAlterar_Categoria = new javax.swing.JButton();
        buttonPesquisar_Tabela_Categoria = new javax.swing.JButton();
        painelProduto = new javax.swing.JPanel();
        label_NOME_PROD = new javax.swing.JLabel();
        NOME_PROD = new javax.swing.JTextField();
        label_MARCA_PROD = new javax.swing.JLabel();
        MARCA_PROD = new javax.swing.JTextField();
        label_QTD_PROD = new javax.swing.JLabel();
        label_VLRUNID_PROD = new javax.swing.JLabel();
        VLRUNID_PROD = new javax.swing.JTextField();
        label_PROD_DES_CAT = new javax.swing.JLabel();
        buttonLimpar_Produto = new javax.swing.JButton();
        QTD_PROD = new javax.swing.JTextField();
        ScrollPane_Produto = new javax.swing.JScrollPane();
        tableProduto = new javax.swing.JTable();
        buttonAdicionar_Produto = new javax.swing.JButton();
        buttonExcluir_Produto = new javax.swing.JButton();
        buttonAlterar_Produto = new javax.swing.JButton();
        buttonPesquisar_Tabela_Produto = new javax.swing.JButton();
        label_PROD_NOME_FOR = new javax.swing.JLabel();
        PROD_DES_CAT = new javax.swing.JComboBox();
        PROD_NOME_FOR = new javax.swing.JComboBox();
        painelServico = new javax.swing.JPanel();
        label_DES_SER = new javax.swing.JLabel();
        DES_SER = new javax.swing.JTextField();
        buttonLimpar_Servico = new javax.swing.JButton();
        buttonAdicionar_Servico = new javax.swing.JButton();
        buttonExcluir_Servico = new javax.swing.JButton();
        buttonAlterar_Servico = new javax.swing.JButton();
        buttonPesquisar_Tabela_Servico = new javax.swing.JButton();
        label_VLR_SER = new javax.swing.JLabel();
        VLR_SER = new javax.swing.JTextField();
        ScrollPane_Produto1 = new javax.swing.JScrollPane();
        tableServico = new javax.swing.JTable();
        painelLogin = new javax.swing.JPanel();
        label_LOGIN_USU = new javax.swing.JLabel();
        LOGIN_USU = new javax.swing.JTextField();
        buttonLimpar_Login = new javax.swing.JButton();
        ScrollPane_Login = new javax.swing.JScrollPane();
        tableLogin = new javax.swing.JTable();
        buttonAdicionar_Login = new javax.swing.JButton();
        buttonExcluir_Login = new javax.swing.JButton();
        buttonAlterar_Login = new javax.swing.JButton();
        buttonPesquisar_Tabela_Login = new javax.swing.JButton();
        label_NOME_USU = new javax.swing.JLabel();
        NOME_USU = new javax.swing.JTextField();
        label_SENHA_USU = new javax.swing.JLabel();
        SENHA_USU = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Papelaria Papelândia - Módulo Cliente");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        painelModuloAdministrativo.setBackground(new java.awt.Color(255, 255, 255));
        painelModuloAdministrativo.setPreferredSize(new java.awt.Dimension(900, 650));
        painelModuloAdministrativo.setRequestFocusEnabled(false);

        imgModuloAdministrativo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgModuloAdministrativo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/moduloAdministrativo.png"))); // NOI18N

        buttonHelp_Administrativo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconhelp.png"))); // NOI18N
        buttonHelp_Administrativo.setPreferredSize(new java.awt.Dimension(35, 35));

        buttonVoltar_Administrativo.setBackground(new java.awt.Color(204, 255, 255));
        buttonVoltar_Administrativo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconexit.png"))); // NOI18N
        buttonVoltar_Administrativo.setPreferredSize(new java.awt.Dimension(35, 35));
        buttonVoltar_Administrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltar_AdministrativoActionPerformed(evt);
            }
        });

        TabelaPaineis_ModuloAdministrativo.setBackground(new java.awt.Color(255, 255, 255));
        TabelaPaineis_ModuloAdministrativo.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        TabelaPaineis_ModuloAdministrativo.setToolTipText("");
        TabelaPaineis_ModuloAdministrativo.setPreferredSize(new java.awt.Dimension(605, 225));

        painelFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        painelFornecedor.setPreferredSize(new java.awt.Dimension(600, 200));

        label_NOME_FOR.setText("Nome: ");

        NOME_FOR.setPreferredSize(new java.awt.Dimension(150, 30));

        label_CNPJ_FOR.setText("CNPJ: ");

        CNPJ_FOR.setPreferredSize(new java.awt.Dimension(140, 30));

        BAI_FOR.setPreferredSize(new java.awt.Dimension(100, 30));

        label_END_FOR.setText("Endereço: ");

        label_CID_FOR.setText("Cidade: ");

        CID_FOR.setPreferredSize(new java.awt.Dimension(100, 30));

        label_UF_FOR.setText("UF: ");

        label_DDDTEL_FOR.setText("DDD: ");

        DDDTEL_FOR.setPreferredSize(new java.awt.Dimension(100, 30));

        label_TEL_FOR.setText("TEL: ");

        TEL_FOR.setPreferredSize(new java.awt.Dimension(100, 30));

        label_EMAIL_FOR.setText("Email: ");

        EMAIL_FOR.setText("email@dominio.com");
        EMAIL_FOR.setPreferredSize(new java.awt.Dimension(100, 30));

        buttonLimpar_Fornecedor.setBackground(new java.awt.Color(204, 255, 255));
        buttonLimpar_Fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconclean.png"))); // NOI18N
        buttonLimpar_Fornecedor.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonLimpar_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimpar_FornecedorActionPerformed(evt);
            }
        });

        UF_FOR.setMaximumRowCount(10);
        UF_FOR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        END_FOR.setPreferredSize(new java.awt.Dimension(100, 30));

        label_BAI_FOR.setText("Bairro: ");

        label_CEP_FOR.setText("CEP: ");

        CEP_FOR.setPreferredSize(new java.awt.Dimension(100, 30));

        buttonAdicionar_Fornecedor.setBackground(new java.awt.Color(204, 255, 255));
        buttonAdicionar_Fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconadd.png"))); // NOI18N
        buttonAdicionar_Fornecedor.setPreferredSize(new java.awt.Dimension(100, 50));
        buttonAdicionar_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionar_FornecedorActionPerformed(evt);
            }
        });

        buttonExcluir_Fornecedor.setBackground(new java.awt.Color(204, 255, 255));
        buttonExcluir_Fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icondelete.png"))); // NOI18N
        buttonExcluir_Fornecedor.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonExcluir_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluir_FornecedorActionPerformed(evt);
            }
        });

        buttonAlterar_Fornecedor.setBackground(new java.awt.Color(204, 255, 255));
        buttonAlterar_Fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconupdate.png"))); // NOI18N
        buttonAlterar_Fornecedor.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonAlterar_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterar_FornecedorActionPerformed(evt);
            }
        });

        buttonPesquisar_Tabela_Fornecedor.setBackground(new java.awt.Color(204, 255, 255));
        buttonPesquisar_Tabela_Fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconsearch.png"))); // NOI18N
        buttonPesquisar_Tabela_Fornecedor.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonPesquisar_Tabela_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisar_Tabela_FornecedorActionPerformed(evt);
            }
        });

        label_NUMEND_FOR.setText("Nº:");

        NUMEND_FOR.setPreferredSize(new java.awt.Dimension(100, 30));

        label_COMPEND_FOR.setText("Complemento: ");

        COMPEND_FOR.setPreferredSize(new java.awt.Dimension(100, 30));

        label_STATUS_FOR.setText("Status: ");

        STATUS_FOR.setMaximumRowCount(10);
        STATUS_FOR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo" }));

        tableFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "CNPJ", "EMPRESA", "ENDEREÇO", "Nº", "COMPLEMENTO", "BAIRRO", "CEP", "CIDADE", "UF", "DDD", "TEL", "EMAIL", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableFornecedor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFornecedorMouseClicked(evt);
            }
        });
        ScrollPane_Fornecedor.setViewportView(tableFornecedor);
        if (tableFornecedor.getColumnModel().getColumnCount() > 0) {
            tableFornecedor.getColumnModel().getColumn(5).setResizable(false);
            tableFornecedor.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout painelFornecedorLayout = new javax.swing.GroupLayout(painelFornecedor);
        painelFornecedor.setLayout(painelFornecedorLayout);
        painelFornecedorLayout.setHorizontalGroup(
            painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelFornecedorLayout.createSequentialGroup()
                        .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(painelFornecedorLayout.createSequentialGroup()
                                .addComponent(label_COMPEND_FOR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(COMPEND_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelFornecedorLayout.createSequentialGroup()
                                .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_END_FOR)
                                    .addComponent(label_CID_FOR))
                                .addGap(10, 10, 10)
                                .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CID_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(END_FOR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(painelFornecedorLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_NOME_FOR)
                                    .addComponent(label_CNPJ_FOR))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CNPJ_FOR, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(NOME_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                        .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFornecedorLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_UF_FOR)
                                .addGap(18, 18, 18)
                                .addComponent(UF_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_CEP_FOR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CEP_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelFornecedorLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelFornecedorLayout.createSequentialGroup()
                                        .addComponent(label_EMAIL_FOR)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EMAIL_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(painelFornecedorLayout.createSequentialGroup()
                                        .addComponent(label_DDDTEL_FOR)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DDDTEL_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(label_TEL_FOR)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TEL_FOR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFornecedorLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(label_NUMEND_FOR)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(NUMEND_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(label_BAI_FOR)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BAI_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(painelFornecedorLayout.createSequentialGroup()
                        .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelFornecedorLayout.createSequentialGroup()
                                .addComponent(buttonAdicionar_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonExcluir_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonAlterar_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonLimpar_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonPesquisar_Tabela_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelFornecedorLayout.createSequentialGroup()
                                .addComponent(label_STATUS_FOR)
                                .addGap(18, 18, 18)
                                .addComponent(STATUS_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelFornecedorLayout.setVerticalGroup(
            painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ScrollPane_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelFornecedorLayout.createSequentialGroup()
                        .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelFornecedorLayout.createSequentialGroup()
                                .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_NOME_FOR)
                                    .addComponent(NOME_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_CNPJ_FOR)
                                    .addComponent(CNPJ_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(CEP_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label_CEP_FOR)
                                        .addComponent(UF_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label_UF_FOR))
                                    .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(END_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label_END_FOR)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_CID_FOR)
                                    .addComponent(CID_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(painelFornecedorLayout.createSequentialGroup()
                                .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_NUMEND_FOR)
                                    .addComponent(NUMEND_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_BAI_FOR)
                                    .addComponent(BAI_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_DDDTEL_FOR)
                                    .addComponent(DDDTEL_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TEL_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_TEL_FOR))))
                        .addGap(11, 11, 11)
                        .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(COMPEND_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_COMPEND_FOR)
                            .addComponent(EMAIL_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_EMAIL_FOR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(STATUS_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_STATUS_FOR))
                        .addGap(25, 25, 25)
                        .addGroup(painelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonAdicionar_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonExcluir_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAlterar_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonPesquisar_Tabela_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonLimpar_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabelaPaineis_ModuloAdministrativo.addTab("Fornecedor", painelFornecedor);

        painelCategoria.setBackground(new java.awt.Color(255, 255, 255));
        painelCategoria.setPreferredSize(new java.awt.Dimension(600, 200));

        label_DES_CAT.setText("Descrição: ");

        DES_CAT.setPreferredSize(new java.awt.Dimension(150, 30));

        buttonLimpar_Categoria.setBackground(new java.awt.Color(204, 255, 255));
        buttonLimpar_Categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconclean.png"))); // NOI18N
        buttonLimpar_Categoria.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonLimpar_Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimpar_CategoriaActionPerformed(evt);
            }
        });

        DefaultTableModel modeloCategoria = new DefaultTableModel();
        tableCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "CATEGORIA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        modeloCategoria.addColumn("Identificador");
        modeloCategoria.addColumn("Categoria");
        tableCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCategoriaMouseClicked(evt);
            }
        });
        ScrollPane_Categoria.setViewportView(tableCategoria);
        if (tableCategoria.getColumnModel().getColumnCount() > 0) {
            tableCategoria.getColumnModel().getColumn(1).setResizable(false);
        }

        buttonAdicionar_Categoria.setBackground(new java.awt.Color(204, 255, 255));
        buttonAdicionar_Categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconadd.png"))); // NOI18N
        buttonAdicionar_Categoria.setPreferredSize(new java.awt.Dimension(100, 50));
        buttonAdicionar_Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionar_CategoriaActionPerformed(evt);
            }
        });

        buttonExcluir_Categoria.setBackground(new java.awt.Color(204, 255, 255));
        buttonExcluir_Categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icondelete.png"))); // NOI18N
        buttonExcluir_Categoria.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonExcluir_Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluir_CategoriaActionPerformed(evt);
            }
        });

        buttonAlterar_Categoria.setBackground(new java.awt.Color(204, 255, 255));
        buttonAlterar_Categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconupdate.png"))); // NOI18N
        buttonAlterar_Categoria.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonAlterar_Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterar_CategoriaActionPerformed(evt);
            }
        });

        buttonPesquisar_Tabela_Categoria.setBackground(new java.awt.Color(204, 255, 255));
        buttonPesquisar_Tabela_Categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconsearch.png"))); // NOI18N
        buttonPesquisar_Tabela_Categoria.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonPesquisar_Tabela_Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisar_Tabela_CategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCategoriaLayout = new javax.swing.GroupLayout(painelCategoria);
        painelCategoria.setLayout(painelCategoriaLayout);
        painelCategoriaLayout.setHorizontalGroup(
            painelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCategoriaLayout.createSequentialGroup()
                .addGroup(painelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCategoriaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(label_DES_CAT)
                        .addGap(25, 25, 25)
                        .addComponent(DES_CAT, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelCategoriaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonAdicionar_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonExcluir_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAlterar_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonLimpar_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPesquisar_Tabela_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ScrollPane_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelCategoriaLayout.setVerticalGroup(
            painelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelCategoriaLayout.createSequentialGroup()
                        .addGroup(painelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_DES_CAT)
                            .addComponent(DES_CAT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonAdicionar_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonExcluir_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAlterar_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonPesquisar_Tabela_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonLimpar_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ScrollPane_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabelaPaineis_ModuloAdministrativo.addTab("Categoria", painelCategoria);

        painelProduto.setBackground(new java.awt.Color(255, 255, 255));
        painelProduto.setPreferredSize(new java.awt.Dimension(600, 200));

        label_NOME_PROD.setText("Nome: ");

        NOME_PROD.setPreferredSize(new java.awt.Dimension(150, 30));

        label_MARCA_PROD.setText("Marca: ");

        MARCA_PROD.setPreferredSize(new java.awt.Dimension(140, 30));

        label_QTD_PROD.setText("Quantidade: ");

        label_VLRUNID_PROD.setText("Valor: ");

        VLRUNID_PROD.setPreferredSize(new java.awt.Dimension(100, 30));

        label_PROD_DES_CAT.setText("Categoria: ");

        buttonLimpar_Produto.setBackground(new java.awt.Color(204, 255, 255));
        buttonLimpar_Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconclean.png"))); // NOI18N
        buttonLimpar_Produto.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonLimpar_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimpar_ProdutoActionPerformed(evt);
            }
        });

        QTD_PROD.setPreferredSize(new java.awt.Dimension(100, 30));

        tableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "PRODUTO", "CATEGORIA", "QTD", "VALOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProdutoMouseClicked(evt);
            }
        });
        ScrollPane_Produto.setViewportView(tableProduto);
        if (tableProduto.getColumnModel().getColumnCount() > 0) {
            tableProduto.getColumnModel().getColumn(0).setResizable(false);
            tableProduto.getColumnModel().getColumn(1).setResizable(false);
            tableProduto.getColumnModel().getColumn(2).setResizable(false);
            tableProduto.getColumnModel().getColumn(3).setResizable(false);
            tableProduto.getColumnModel().getColumn(4).setResizable(false);
        }

        buttonAdicionar_Produto.setBackground(new java.awt.Color(204, 255, 255));
        buttonAdicionar_Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconadd.png"))); // NOI18N
        buttonAdicionar_Produto.setPreferredSize(new java.awt.Dimension(100, 50));
        buttonAdicionar_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionar_ProdutoActionPerformed(evt);
            }
        });

        buttonExcluir_Produto.setBackground(new java.awt.Color(204, 255, 255));
        buttonExcluir_Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icondelete.png"))); // NOI18N
        buttonExcluir_Produto.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonExcluir_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluir_ProdutoActionPerformed(evt);
            }
        });

        buttonAlterar_Produto.setBackground(new java.awt.Color(204, 255, 255));
        buttonAlterar_Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconupdate.png"))); // NOI18N
        buttonAlterar_Produto.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonAlterar_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterar_ProdutoActionPerformed(evt);
            }
        });

        buttonPesquisar_Tabela_Produto.setBackground(new java.awt.Color(204, 255, 255));
        buttonPesquisar_Tabela_Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconsearch.png"))); // NOI18N
        buttonPesquisar_Tabela_Produto.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonPesquisar_Tabela_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisar_Tabela_ProdutoActionPerformed(evt);
            }
        });

        label_PROD_NOME_FOR.setText("Fornecedor: ");

        PROD_DES_CAT.setPreferredSize(new java.awt.Dimension(110, 30));
        controller.CategoriaDAO categoriaDAO = new controller.CategoriaDAO();
        categoriaDAO.comboCategoria(this.PROD_DES_CAT);
        PROD_DES_CAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PROD_DES_CATActionPerformed(evt);
            }
        });

        PROD_NOME_FOR.setPreferredSize(new java.awt.Dimension(110, 30));
        controller.FornecedorDAO fornecedorDAO = new controller.FornecedorDAO();
        fornecedorDAO.comboFornecedor(this.PROD_NOME_FOR);
        PROD_NOME_FOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PROD_NOME_FORActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelProdutoLayout = new javax.swing.GroupLayout(painelProduto);
        painelProduto.setLayout(painelProdutoLayout);
        painelProdutoLayout.setHorizontalGroup(
            painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelProdutoLayout.createSequentialGroup()
                        .addComponent(buttonAdicionar_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonExcluir_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAlterar_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonLimpar_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPesquisar_Tabela_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelProdutoLayout.createSequentialGroup()
                        .addGroup(painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(painelProdutoLayout.createSequentialGroup()
                                .addGroup(painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_QTD_PROD)
                                    .addComponent(label_VLRUNID_PROD))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(QTD_PROD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(VLRUNID_PROD, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MARCA_PROD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(painelProdutoLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_MARCA_PROD)
                                    .addGroup(painelProdutoLayout.createSequentialGroup()
                                        .addComponent(label_NOME_PROD)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(NOME_PROD, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelProdutoLayout.createSequentialGroup()
                                .addComponent(label_PROD_DES_CAT)
                                .addGap(18, 18, 18)
                                .addComponent(PROD_DES_CAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelProdutoLayout.createSequentialGroup()
                                .addComponent(label_PROD_NOME_FOR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PROD_NOME_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(ScrollPane_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelProdutoLayout.setVerticalGroup(
            painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelProdutoLayout.createSequentialGroup()
                        .addGroup(painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_NOME_PROD)
                            .addComponent(NOME_PROD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label_PROD_DES_CAT)
                                .addComponent(MARCA_PROD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PROD_DES_CAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label_MARCA_PROD))
                        .addGap(11, 11, 11)
                        .addGroup(painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(QTD_PROD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_QTD_PROD)
                            .addComponent(label_PROD_NOME_FOR)
                            .addComponent(PROD_NOME_FOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_VLRUNID_PROD)
                            .addComponent(VLRUNID_PROD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)
                        .addGroup(painelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonAdicionar_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonExcluir_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAlterar_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonPesquisar_Tabela_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonLimpar_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ScrollPane_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabelaPaineis_ModuloAdministrativo.addTab("Produto", painelProduto);

        painelServico.setBackground(new java.awt.Color(255, 255, 255));
        painelServico.setPreferredSize(new java.awt.Dimension(600, 200));

        label_DES_SER.setText("Descrição: ");

        DES_SER.setPreferredSize(new java.awt.Dimension(150, 30));

        buttonLimpar_Servico.setBackground(new java.awt.Color(204, 255, 255));
        buttonLimpar_Servico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconclean.png"))); // NOI18N
        buttonLimpar_Servico.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonLimpar_Servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimpar_ServicoActionPerformed(evt);
            }
        });

        buttonAdicionar_Servico.setBackground(new java.awt.Color(204, 255, 255));
        buttonAdicionar_Servico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconadd.png"))); // NOI18N
        buttonAdicionar_Servico.setPreferredSize(new java.awt.Dimension(100, 50));
        buttonAdicionar_Servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionar_ServicoActionPerformed(evt);
            }
        });

        buttonExcluir_Servico.setBackground(new java.awt.Color(204, 255, 255));
        buttonExcluir_Servico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icondelete.png"))); // NOI18N
        buttonExcluir_Servico.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonExcluir_Servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluir_ServicoActionPerformed(evt);
            }
        });

        buttonAlterar_Servico.setBackground(new java.awt.Color(204, 255, 255));
        buttonAlterar_Servico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconupdate.png"))); // NOI18N
        buttonAlterar_Servico.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonAlterar_Servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterar_ServicoActionPerformed(evt);
            }
        });

        buttonPesquisar_Tabela_Servico.setBackground(new java.awt.Color(204, 255, 255));
        buttonPesquisar_Tabela_Servico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconsearch.png"))); // NOI18N
        buttonPesquisar_Tabela_Servico.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonPesquisar_Tabela_Servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisar_Tabela_ServicoActionPerformed(evt);
            }
        });

        label_VLR_SER.setText("Valor: ");

        VLR_SER.setPreferredSize(new java.awt.Dimension(150, 30));

        tableServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "SERVIÇO", "VALOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableServicoMouseClicked(evt);
            }
        });
        ScrollPane_Produto1.setViewportView(tableServico);
        if (tableServico.getColumnModel().getColumnCount() > 0) {
            tableServico.getColumnModel().getColumn(0).setResizable(false);
            tableServico.getColumnModel().getColumn(1).setResizable(false);
            tableServico.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout painelServicoLayout = new javax.swing.GroupLayout(painelServico);
        painelServico.setLayout(painelServicoLayout);
        painelServicoLayout.setHorizontalGroup(
            painelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelServicoLayout.createSequentialGroup()
                .addGroup(painelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelServicoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonAdicionar_Servico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonExcluir_Servico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAlterar_Servico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonLimpar_Servico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPesquisar_Tabela_Servico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelServicoLayout.createSequentialGroup()
                        .addGroup(painelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelServicoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(label_DES_SER))
                            .addGroup(painelServicoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(label_VLR_SER)))
                        .addGap(25, 25, 25)
                        .addGroup(painelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VLR_SER, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DES_SER, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(ScrollPane_Produto1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelServicoLayout.setVerticalGroup(
            painelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelServicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPane_Produto1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelServicoLayout.createSequentialGroup()
                        .addGroup(painelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_DES_SER)
                            .addComponent(DES_SER, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_VLR_SER)
                            .addComponent(VLR_SER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(159, 159, 159)
                        .addGroup(painelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonAdicionar_Servico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonExcluir_Servico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAlterar_Servico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonPesquisar_Tabela_Servico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonLimpar_Servico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabelaPaineis_ModuloAdministrativo.addTab("Serviço", painelServico);

        painelLogin.setBackground(new java.awt.Color(255, 255, 255));
        painelLogin.setPreferredSize(new java.awt.Dimension(600, 200));

        label_LOGIN_USU.setText("Login:");

        LOGIN_USU.setPreferredSize(new java.awt.Dimension(150, 30));

        buttonLimpar_Login.setBackground(new java.awt.Color(204, 255, 255));
        buttonLimpar_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconclean.png"))); // NOI18N
        buttonLimpar_Login.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonLimpar_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimpar_LoginActionPerformed(evt);
            }
        });

        tableLogin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LOGIN", "NOME"
            }
        ));
        tableLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLoginMouseClicked(evt);
            }
        });
        ScrollPane_Login.setViewportView(tableLogin);

        buttonAdicionar_Login.setBackground(new java.awt.Color(204, 255, 255));
        buttonAdicionar_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconadd.png"))); // NOI18N
        buttonAdicionar_Login.setPreferredSize(new java.awt.Dimension(100, 50));
        buttonAdicionar_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionar_LoginActionPerformed(evt);
            }
        });

        buttonExcluir_Login.setBackground(new java.awt.Color(204, 255, 255));
        buttonExcluir_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icondelete.png"))); // NOI18N
        buttonExcluir_Login.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonExcluir_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluir_LoginActionPerformed(evt);
            }
        });

        buttonAlterar_Login.setBackground(new java.awt.Color(204, 255, 255));
        buttonAlterar_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconupdate.png"))); // NOI18N
        buttonAlterar_Login.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonAlterar_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterar_LoginActionPerformed(evt);
            }
        });

        buttonPesquisar_Tabela_Login.setBackground(new java.awt.Color(204, 255, 255));
        buttonPesquisar_Tabela_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconsearch.png"))); // NOI18N
        buttonPesquisar_Tabela_Login.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonPesquisar_Tabela_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisar_Tabela_LoginActionPerformed(evt);
            }
        });

        label_NOME_USU.setText("Nome: ");

        NOME_USU.setPreferredSize(new java.awt.Dimension(150, 30));

        label_SENHA_USU.setText("Senha: ");

        SENHA_USU.setPreferredSize(new java.awt.Dimension(150, 30));

        javax.swing.GroupLayout painelLoginLayout = new javax.swing.GroupLayout(painelLogin);
        painelLogin.setLayout(painelLoginLayout);
        painelLoginLayout.setHorizontalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonAdicionar_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonExcluir_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAlterar_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonLimpar_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPesquisar_Tabela_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(416, 652, Short.MAX_VALUE))
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLoginLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_NOME_USU)
                            .addComponent(label_LOGIN_USU)))
                    .addGroup(painelLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_SENHA_USU)))
                .addGap(18, 18, 18)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(LOGIN_USU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NOME_USU, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SENHA_USU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ScrollPane_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelLoginLayout.setVerticalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelLoginLayout.createSequentialGroup()
                        .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_NOME_USU)
                            .addComponent(NOME_USU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_LOGIN_USU)
                            .addComponent(LOGIN_USU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_SENHA_USU)
                            .addComponent(SENHA_USU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonAdicionar_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonExcluir_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAlterar_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonPesquisar_Tabela_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonLimpar_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ScrollPane_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabelaPaineis_ModuloAdministrativo.addTab("Usuários do Sistema", painelLogin);

        javax.swing.GroupLayout painelModuloAdministrativoLayout = new javax.swing.GroupLayout(painelModuloAdministrativo);
        painelModuloAdministrativo.setLayout(painelModuloAdministrativoLayout);
        painelModuloAdministrativoLayout.setHorizontalGroup(
            painelModuloAdministrativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelModuloAdministrativoLayout.createSequentialGroup()
                .addGroup(painelModuloAdministrativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelModuloAdministrativoLayout.createSequentialGroup()
                        .addComponent(imgModuloAdministrativo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelModuloAdministrativoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TabelaPaineis_ModuloAdministrativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelModuloAdministrativoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonHelp_Administrativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonVoltar_Administrativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        painelModuloAdministrativoLayout.setVerticalGroup(
            painelModuloAdministrativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelModuloAdministrativoLayout.createSequentialGroup()
                .addComponent(imgModuloAdministrativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabelaPaineis_ModuloAdministrativo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelModuloAdministrativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonVoltar_Administrativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonHelp_Administrativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelModuloAdministrativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelModuloAdministrativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltar_AdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltar_AdministrativoActionPerformed
    view.MenuPrincipal vMenuPrincipal = new view.MenuPrincipal();
    dispose();
    vMenuPrincipal.setVisible(true);
    }//GEN-LAST:event_buttonVoltar_AdministrativoActionPerformed

    private void buttonPesquisar_Tabela_CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesquisar_Tabela_CategoriaActionPerformed
    controller.CategoriaDAO categoriaDAO = new controller.CategoriaDAO();
    model.Categoria mCategoria = new model.Categoria();
    categoriaDAO.pesquisarTabela_Categoria(this, mCategoria);
    }//GEN-LAST:event_buttonPesquisar_Tabela_CategoriaActionPerformed

    private void buttonAlterar_CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterar_CategoriaActionPerformed
    controller.CategoriaDAO categoriaDAO = new controller.CategoriaDAO();
    model.Categoria mCategoria = new model.Categoria();
    categoriaDAO.atualizarCategoria(this, mCategoria);
    }//GEN-LAST:event_buttonAlterar_CategoriaActionPerformed

    private void buttonExcluir_CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluir_CategoriaActionPerformed
    controller.CategoriaDAO categoriaDAO = new controller.CategoriaDAO();
    model.Categoria mCategoria = new model.Categoria();
    categoriaDAO.excluirCategoria(this, mCategoria);
    }//GEN-LAST:event_buttonExcluir_CategoriaActionPerformed

    private void buttonAdicionar_CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionar_CategoriaActionPerformed
    controller.CategoriaDAO categoriaDAO = new controller.CategoriaDAO();
    model.Categoria mCategoria = new model.Categoria();
    categoriaDAO.getCategoria(this, mCategoria);
    categoriaDAO.adicionarCategoria(this, mCategoria);
    }//GEN-LAST:event_buttonAdicionar_CategoriaActionPerformed

    private void buttonLimpar_CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimpar_CategoriaActionPerformed
    controller.CategoriaDAO categoriaDAO = new controller.CategoriaDAO();
    categoriaDAO.cleanCategoria(this);
    }//GEN-LAST:event_buttonLimpar_CategoriaActionPerformed

    private void buttonPesquisar_Tabela_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesquisar_Tabela_FornecedorActionPerformed
    controller.FornecedorDAO fornecedorDAO = new controller.FornecedorDAO();
    model.Fornecedor mFornecedor = new model.Fornecedor();
    fornecedorDAO.pesquisarTabela_Fornecedor(this, mFornecedor);
    }//GEN-LAST:event_buttonPesquisar_Tabela_FornecedorActionPerformed

    private void buttonAlterar_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterar_FornecedorActionPerformed
    controller.FornecedorDAO fornecedorDAO = new controller.FornecedorDAO();
    model.Fornecedor mFornecedor = new model.Fornecedor();
    fornecedorDAO.atualizarFornecedor(this, mFornecedor);
    }//GEN-LAST:event_buttonAlterar_FornecedorActionPerformed

    private void buttonExcluir_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluir_FornecedorActionPerformed
    controller.FornecedorDAO fornecedorDAO = new controller.FornecedorDAO();
    model.Fornecedor mFornecedor = new model.Fornecedor();
    fornecedorDAO.excluirFornecedor(this, mFornecedor);
    }//GEN-LAST:event_buttonExcluir_FornecedorActionPerformed

    private void buttonAdicionar_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionar_FornecedorActionPerformed
    controller.FornecedorDAO fornecedorDAO = new controller.FornecedorDAO();
    model.Fornecedor mFornecedor = new model.Fornecedor();
    fornecedorDAO.getFornecedor(this, mFornecedor);
    fornecedorDAO.adicionarFornecedor(this, mFornecedor);
    }//GEN-LAST:event_buttonAdicionar_FornecedorActionPerformed

    private void buttonLimpar_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimpar_FornecedorActionPerformed
    controller.FornecedorDAO fornecedorDAO = new controller.FornecedorDAO();
    fornecedorDAO.cleanFornecedor(this);
    }//GEN-LAST:event_buttonLimpar_FornecedorActionPerformed

    private void buttonLimpar_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimpar_ProdutoActionPerformed
    controller.ProdutoDAO produtoDAO = new controller.ProdutoDAO();
    produtoDAO.cleanProduto(this);
    }//GEN-LAST:event_buttonLimpar_ProdutoActionPerformed

    private void buttonAdicionar_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionar_ProdutoActionPerformed
    controller.ProdutoDAO produtoDAO = new controller.ProdutoDAO();
    model.Produto mProduto = new model.Produto();
    model.Categoria mCategoria = new model.Categoria();
    model.Fornecedor mFornecedor = new model.Fornecedor();
    produtoDAO.getProduto(this, mProduto, mCategoria, mFornecedor);
    produtoDAO.adicionarProduto(this, mProduto, mCategoria, mFornecedor);
    }//GEN-LAST:event_buttonAdicionar_ProdutoActionPerformed

    private void buttonExcluir_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluir_ProdutoActionPerformed
    controller.ProdutoDAO produtoDAO = new controller.ProdutoDAO();
    model.Produto mProduto = new model.Produto();
    model.Categoria mCategoria = new model.Categoria();
    model.Fornecedor mFornecedor = new model.Fornecedor();
    produtoDAO.excluirProduto(this, mProduto, mCategoria, mFornecedor);
    }//GEN-LAST:event_buttonExcluir_ProdutoActionPerformed

    private void buttonAlterar_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterar_ProdutoActionPerformed
    controller.ProdutoDAO produtoDAO = new controller.ProdutoDAO();
    model.Produto mProduto = new model.Produto();
    model.Categoria mCategoria = new model.Categoria();
    model.Fornecedor mFornecedor = new model.Fornecedor();
    produtoDAO.atualizarProduto(this, mProduto, mCategoria, mFornecedor);
    }//GEN-LAST:event_buttonAlterar_ProdutoActionPerformed

    private void buttonPesquisar_Tabela_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesquisar_Tabela_ProdutoActionPerformed
    controller.ProdutoDAO produtoDAO = new controller.ProdutoDAO();
    model.Produto mProduto = new model.Produto();
    produtoDAO.pesquisarTabela_Produto(this, mProduto);
    }//GEN-LAST:event_buttonPesquisar_Tabela_ProdutoActionPerformed

    private void buttonLimpar_ServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimpar_ServicoActionPerformed
    controller.ServicoDAO servicoDAO = new controller.ServicoDAO();
    servicoDAO.cleanServico(this);
    }//GEN-LAST:event_buttonLimpar_ServicoActionPerformed

    private void buttonAdicionar_ServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionar_ServicoActionPerformed
    controller.ServicoDAO servicoDAO = new controller.ServicoDAO();
    model.Servico mServico = new model.Servico();
    servicoDAO.getServico(this, mServico);
    servicoDAO.adicionarServico(this, mServico);
    }//GEN-LAST:event_buttonAdicionar_ServicoActionPerformed

    private void buttonExcluir_ServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluir_ServicoActionPerformed
    controller.ServicoDAO servicoDAO = new controller.ServicoDAO();
    model.Servico mServico = new model.Servico();
    servicoDAO.excluirServico(this, mServico);
    }//GEN-LAST:event_buttonExcluir_ServicoActionPerformed

    private void buttonAlterar_ServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterar_ServicoActionPerformed
    controller.ServicoDAO servicoDAO = new controller.ServicoDAO();
    model.Servico mServico = new model.Servico();
    servicoDAO.atualizarServico(this, mServico);
    }//GEN-LAST:event_buttonAlterar_ServicoActionPerformed

    private void buttonPesquisar_Tabela_ServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesquisar_Tabela_ServicoActionPerformed
    controller.ServicoDAO servicoDAO = new controller.ServicoDAO();
    model.Servico mServico = new model.Servico();
    servicoDAO.pesquisarTabela_Servico(this, mServico);
    }//GEN-LAST:event_buttonPesquisar_Tabela_ServicoActionPerformed

    private void buttonLimpar_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimpar_LoginActionPerformed
    controller.LoginDAO loginDAO = new controller.LoginDAO();
    loginDAO.cleanLogin(this);
    }//GEN-LAST:event_buttonLimpar_LoginActionPerformed

    private void buttonAdicionar_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionar_LoginActionPerformed
    controller.LoginDAO loginDAO = new controller.LoginDAO();
    model.Login mLogin = new model.Login();
    loginDAO.adicionarLogin(this, mLogin);
    }//GEN-LAST:event_buttonAdicionar_LoginActionPerformed

    private void buttonExcluir_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluir_LoginActionPerformed
    controller.LoginDAO loginDAO = new controller.LoginDAO();
    model.Login mLogin = new model.Login();
    loginDAO.excluirLogin(this, mLogin);
    }//GEN-LAST:event_buttonExcluir_LoginActionPerformed

    private void buttonAlterar_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterar_LoginActionPerformed
    controller.LoginDAO loginDAO = new controller.LoginDAO();
    model.Login mLogin = new model.Login();
    loginDAO.atualizarLogin(this, mLogin);
    }//GEN-LAST:event_buttonAlterar_LoginActionPerformed

    private void buttonPesquisar_Tabela_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesquisar_Tabela_LoginActionPerformed
    controller.LoginDAO loginDAO = new controller.LoginDAO();
    loginDAO.pesquisarTabela_Login(this);
    }//GEN-LAST:event_buttonPesquisar_Tabela_LoginActionPerformed

    private void tableLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLoginMouseClicked
    controller.LoginDAO loginDAO = new controller.LoginDAO();
    model.Login mLogin = new model.Login();
    loginDAO.getLoginrow(this, mLogin);
    }//GEN-LAST:event_tableLoginMouseClicked

    private void tableFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFornecedorMouseClicked
    controller.FornecedorDAO fornecedorDAO = new controller.FornecedorDAO();
    model.Fornecedor mFornecedor = new model.Fornecedor();
    fornecedorDAO.getFornecedorrow(this, mFornecedor);
    }//GEN-LAST:event_tableFornecedorMouseClicked

    private void PROD_DES_CATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PROD_DES_CATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PROD_DES_CATActionPerformed

    private void tableCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCategoriaMouseClicked
    controller.CategoriaDAO categoriaDAO = new controller.CategoriaDAO();
    model.Categoria mCategoria = new model.Categoria();
    categoriaDAO.getCategoriarow(this, mCategoria);
    }//GEN-LAST:event_tableCategoriaMouseClicked

    private void tableProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProdutoMouseClicked
    controller.ProdutoDAO produtoDAO = new controller.ProdutoDAO();
    model.Produto mProduto = new model.Produto();
    model.Categoria mCategoria = new model.Categoria();
    model.Fornecedor mFornecedor = new model.Fornecedor();
    produtoDAO.getProdutorow(this, mFornecedor, mCategoria, mProduto);
    }//GEN-LAST:event_tableProdutoMouseClicked

    private void PROD_NOME_FORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PROD_NOME_FORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PROD_NOME_FORActionPerformed

    private void tableServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableServicoMouseClicked
    controller.ServicoDAO servicoDAO = new controller.ServicoDAO();
    model.Servico mServico = new model.Servico();
    servicoDAO.pesquisarServico(this, mServico, "sim");
    }//GEN-LAST:event_tableServicoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            getLogger(ModuloAdministrativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
            new ModuloAdministrativo().setVisible(true);
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField BAI_FOR;
    public javax.swing.JTextField CEP_FOR;
    public javax.swing.JTextField CID_FOR;
    public javax.swing.JTextField CNPJ_FOR;
    public javax.swing.JTextField COMPEND_FOR;
    public javax.swing.JTextField DDDTEL_FOR;
    public javax.swing.JTextField DES_CAT;
    public javax.swing.JTextField DES_SER;
    public javax.swing.JTextField EMAIL_FOR;
    public javax.swing.JTextField END_FOR;
    public javax.swing.JTextField LOGIN_USU;
    public javax.swing.JTextField MARCA_PROD;
    public javax.swing.JTextField NOME_FOR;
    public javax.swing.JTextField NOME_PROD;
    public javax.swing.JTextField NOME_USU;
    public javax.swing.JTextField NUMEND_FOR;
    public javax.swing.JComboBox PROD_DES_CAT;
    public javax.swing.JComboBox PROD_NOME_FOR;
    public javax.swing.JTextField QTD_PROD;
    public javax.swing.JPasswordField SENHA_USU;
    public javax.swing.JComboBox STATUS_FOR;
    private javax.swing.JScrollPane ScrollPane_Categoria;
    private javax.swing.JScrollPane ScrollPane_Fornecedor;
    private javax.swing.JScrollPane ScrollPane_Login;
    private javax.swing.JScrollPane ScrollPane_Produto;
    private javax.swing.JScrollPane ScrollPane_Produto1;
    public javax.swing.JTextField TEL_FOR;
    public javax.swing.JTabbedPane TabelaPaineis_ModuloAdministrativo;
    public javax.swing.JComboBox UF_FOR;
    public javax.swing.JTextField VLRUNID_PROD;
    public javax.swing.JTextField VLR_SER;
    private javax.swing.JButton buttonAdicionar_Categoria;
    private javax.swing.JButton buttonAdicionar_Fornecedor;
    private javax.swing.JButton buttonAdicionar_Login;
    private javax.swing.JButton buttonAdicionar_Produto;
    private javax.swing.JButton buttonAdicionar_Servico;
    private javax.swing.JButton buttonAlterar_Categoria;
    private javax.swing.JButton buttonAlterar_Fornecedor;
    private javax.swing.JButton buttonAlterar_Login;
    private javax.swing.JButton buttonAlterar_Produto;
    private javax.swing.JButton buttonAlterar_Servico;
    private javax.swing.JButton buttonExcluir_Categoria;
    private javax.swing.JButton buttonExcluir_Fornecedor;
    private javax.swing.JButton buttonExcluir_Login;
    private javax.swing.JButton buttonExcluir_Produto;
    private javax.swing.JButton buttonExcluir_Servico;
    private javax.swing.JButton buttonHelp_Administrativo;
    private javax.swing.JButton buttonLimpar_Categoria;
    private javax.swing.JButton buttonLimpar_Fornecedor;
    private javax.swing.JButton buttonLimpar_Login;
    private javax.swing.JButton buttonLimpar_Produto;
    private javax.swing.JButton buttonLimpar_Servico;
    private javax.swing.JButton buttonPesquisar_Tabela_Categoria;
    private javax.swing.JButton buttonPesquisar_Tabela_Fornecedor;
    private javax.swing.JButton buttonPesquisar_Tabela_Login;
    private javax.swing.JButton buttonPesquisar_Tabela_Produto;
    private javax.swing.JButton buttonPesquisar_Tabela_Servico;
    private javax.swing.JButton buttonVoltar_Administrativo;
    private javax.swing.JLabel imgModuloAdministrativo;
    private javax.swing.JLabel label_BAI_FOR;
    private javax.swing.JLabel label_CEP_FOR;
    private javax.swing.JLabel label_CID_FOR;
    private javax.swing.JLabel label_CNPJ_FOR;
    private javax.swing.JLabel label_COMPEND_FOR;
    private javax.swing.JLabel label_DDDTEL_FOR;
    private javax.swing.JLabel label_DES_CAT;
    private javax.swing.JLabel label_DES_SER;
    private javax.swing.JLabel label_EMAIL_FOR;
    private javax.swing.JLabel label_END_FOR;
    private javax.swing.JLabel label_LOGIN_USU;
    private javax.swing.JLabel label_MARCA_PROD;
    private javax.swing.JLabel label_NOME_FOR;
    private javax.swing.JLabel label_NOME_PROD;
    private javax.swing.JLabel label_NOME_USU;
    private javax.swing.JLabel label_NUMEND_FOR;
    private javax.swing.JLabel label_PROD_DES_CAT;
    private javax.swing.JLabel label_PROD_NOME_FOR;
    private javax.swing.JLabel label_QTD_PROD;
    private javax.swing.JLabel label_SENHA_USU;
    private javax.swing.JLabel label_STATUS_FOR;
    private javax.swing.JLabel label_TEL_FOR;
    private javax.swing.JLabel label_UF_FOR;
    private javax.swing.JLabel label_VLRUNID_PROD;
    private javax.swing.JLabel label_VLR_SER;
    public javax.swing.JPanel painelCategoria;
    public javax.swing.JPanel painelFornecedor;
    public javax.swing.JPanel painelLogin;
    public javax.swing.JPanel painelModuloAdministrativo;
    public javax.swing.JPanel painelProduto;
    public javax.swing.JPanel painelServico;
    public javax.swing.JTable tableCategoria;
    public javax.swing.JTable tableFornecedor;
    public javax.swing.JTable tableLogin;
    public javax.swing.JTable tableProduto;
    public javax.swing.JTable tableServico;
    // End of variables declaration//GEN-END:variables
    private static final Logger LOG = getLogger(ModuloAdministrativo.class.getName());
}
