package view;

import controller.VendedorDAO;
import java.util.logging.Logger;
import static java.util.logging.Logger.getLogger;
import javax.swing.JFormattedTextField;
import static javax.swing.UIManager.getInstalledLookAndFeels;
import static javax.swing.UIManager.setLookAndFeel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import static java.util.logging.Logger.getLogger;
import static javax.swing.UIManager.setLookAndFeel;

/**
 *
 * @author INFOLUCK
 */
public class ModuloVendedor extends javax.swing.JFrame {

    /**
     * Creates new form cliente
     */
    public ModuloVendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelModuloVendedor = new javax.swing.JPanel();
        imgModuloVendedor = new javax.swing.JLabel();
        buttonHelp_Vendedor = new javax.swing.JButton();
        buttonVoltarVendedor = new javax.swing.JButton();
        TabelaPaineis_ModuloVendedor = new javax.swing.JTabbedPane();
        painelVendedor = new javax.swing.JPanel();
        label_NOME_VEN = new javax.swing.JLabel();
        NOME_VEN = new javax.swing.JTextField();
        label_CPF_VEN = new javax.swing.JLabel();
        CPF_VEN = new javax.swing.JTextField();
        try{
            MaskFormatter CPF = new
            MaskFormatter("###.###.###-##");
            CPF_VEN = new JFormattedTextField(CPF);
        }
        catch(Exception e){

        }
        BAI_VEN = new javax.swing.JTextField();
        label_END_VEN = new javax.swing.JLabel();
        label_CID_CLI = new javax.swing.JLabel();
        CID_VEN = new javax.swing.JTextField();
        label_UF_VEN = new javax.swing.JLabel();
        label_DDDTEL_VEN = new javax.swing.JLabel();
        DDDTEL_VEN = new javax.swing.JTextField();
        try{
            MaskFormatter DDD = new
            MaskFormatter("##");
            DDDTEL_VEN = new JFormattedTextField(DDD);
        }
        catch(Exception e){

        }
        label_TEL_VEN = new javax.swing.JLabel();
        TEL_VEN = new javax.swing.JTextField();
        try{
            MaskFormatter Telefone = new
            MaskFormatter("####-####");
            TEL_VEN = new JFormattedTextField(Telefone);
        }
        catch(Exception e){

        }
        label_EMAIL_VEN = new javax.swing.JLabel();
        EMAIL_VEN = new javax.swing.JTextField();
        buttonLimpar_Vendedor = new javax.swing.JButton();
        UF_VEN = new javax.swing.JComboBox();
        SEX_VEN = new javax.swing.JComboBox();
        label_SEX_VEN = new javax.swing.JLabel();
        END_VEN = new javax.swing.JTextField();
        label_BAI_VEN = new javax.swing.JLabel();
        label_CEP_VEN = new javax.swing.JLabel();
        CEP_VEN = new javax.swing.JTextField();
        try{
            MaskFormatter CEP = new
            MaskFormatter("#####-###");
            CEP_VEN = new JFormattedTextField(CEP);
        }
        catch(Exception e){

        }
        label_DTNASC_VEN = new javax.swing.JLabel();
        DATNASC_VEN = new javax.swing.JTextField();
        try{
            MaskFormatter data = new
            MaskFormatter("##/##/####");
            DATNASC_VEN = new JFormattedTextField(data);
        }
        catch(Exception e){

        }
        buttonAdicionar_Vendedor = new javax.swing.JButton();
        buttonExcluir_Vendedor = new javax.swing.JButton();
        buttonAlterar_Vendedor = new javax.swing.JButton();
        buttonPesquisar_Tabela_Vendedor = new javax.swing.JButton();
        label_NUMEND_VEN = new javax.swing.JLabel();
        NUMEND_VEN = new javax.swing.JTextField();
        try{
            MaskFormatter DDD = new
            MaskFormatter("##");
            DDDTEL_VEN = new JFormattedTextField(DDD);
        }
        catch(Exception e){

        }
        label_COMPEND_VEN = new javax.swing.JLabel();
        COMPEND_VEN = new javax.swing.JTextField();
        try{
            MaskFormatter DDD = new
            MaskFormatter("##");
            DDDTEL_VEN = new JFormattedTextField(DDD);
        }
        catch(Exception e){

        }
        ScrollPane_Fornecedor = new javax.swing.JScrollPane();
        tableVendedor = new javax.swing.JTable();
        painelHistoricoServico = new javax.swing.JPanel();
        label_HISSER_COD_NOTFIS = new javax.swing.JLabel();
        label_HISSER_COD_SER = new javax.swing.JLabel();
        buttonLimpar_HistoricoServico = new javax.swing.JButton();
        ScrollPane_HistoricoServico = new javax.swing.JScrollPane();
        tableHistoricoServico = new javax.swing.JTable();
        buttonAdicionar_HistoricoServico = new javax.swing.JButton();
        buttonExcluir_HistoricoServico = new javax.swing.JButton();
        buttonAlterar_HistoricoServico = new javax.swing.JButton();
        buttonPesquisar_Tabela_HistoricoServico = new javax.swing.JButton();
        label_PES_COD_HISSER = new javax.swing.JLabel();
        buttonPesquisar_COD_HISSER = new javax.swing.JButton();
        label_DES_HISSER = new javax.swing.JLabel();
        DES_HISSER = new javax.swing.JTextField();
        HISSER_COD_NOTFIS = new javax.swing.JComboBox();
        HISSER_DES_SER = new javax.swing.JComboBox();
        PES_COD_HISSER = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Papelaria Papelândia - Módulo Cliente");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        painelModuloVendedor.setBackground(new java.awt.Color(255, 255, 255));
        painelModuloVendedor.setPreferredSize(new java.awt.Dimension(900, 650));
        painelModuloVendedor.setRequestFocusEnabled(false);

        imgModuloVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/moduloVendedor.png"))); // NOI18N

        buttonHelp_Vendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconhelp.png"))); // NOI18N
        buttonHelp_Vendedor.setPreferredSize(new java.awt.Dimension(35, 35));

        buttonVoltarVendedor.setBackground(new java.awt.Color(204, 255, 255));
        buttonVoltarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconexit.png"))); // NOI18N
        buttonVoltarVendedor.setPreferredSize(new java.awt.Dimension(35, 35));
        buttonVoltarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarVendedorActionPerformed(evt);
            }
        });

        TabelaPaineis_ModuloVendedor.setBackground(new java.awt.Color(255, 255, 255));
        TabelaPaineis_ModuloVendedor.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        TabelaPaineis_ModuloVendedor.setToolTipText("");
        TabelaPaineis_ModuloVendedor.setPreferredSize(new java.awt.Dimension(605, 350));

        painelVendedor.setBackground(new java.awt.Color(255, 255, 255));
        painelVendedor.setPreferredSize(new java.awt.Dimension(600, 200));

        label_NOME_VEN.setText("Nome: ");

        NOME_VEN.setPreferredSize(new java.awt.Dimension(150, 30));

        label_CPF_VEN.setText("CPF: ");

        CPF_VEN.setPreferredSize(new java.awt.Dimension(140, 30));

        BAI_VEN.setPreferredSize(new java.awt.Dimension(100, 30));

        label_END_VEN.setText("Endereço: ");

        label_CID_CLI.setText("Cidade: ");

        CID_VEN.setPreferredSize(new java.awt.Dimension(100, 30));

        label_UF_VEN.setText("UF: ");

        label_DDDTEL_VEN.setText("DDD: ");

        DDDTEL_VEN.setPreferredSize(new java.awt.Dimension(100, 30));

        label_TEL_VEN.setText("TEL: ");

        TEL_VEN.setPreferredSize(new java.awt.Dimension(100, 30));

        label_EMAIL_VEN.setText("Email: ");

        EMAIL_VEN.setText("email@dominio.com");
        EMAIL_VEN.setPreferredSize(new java.awt.Dimension(100, 30));

        buttonLimpar_Vendedor.setBackground(new java.awt.Color(204, 255, 255));
        buttonLimpar_Vendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconclean.png"))); // NOI18N
        buttonLimpar_Vendedor.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonLimpar_Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimpar_VendedorActionPerformed(evt);
            }
        });

        UF_VEN.setMaximumRowCount(10);
        UF_VEN.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        SEX_VEN.setMaximumRowCount(4);
        SEX_VEN.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        SEX_VEN.setToolTipText("");

        label_SEX_VEN.setText("Sexo: ");

        END_VEN.setPreferredSize(new java.awt.Dimension(100, 30));

        label_BAI_VEN.setText("Bairro: ");

        label_CEP_VEN.setText("CEP: ");

        CEP_VEN.setPreferredSize(new java.awt.Dimension(100, 30));

        label_DTNASC_VEN.setText("Data Nasc.");

        DATNASC_VEN.setPreferredSize(new java.awt.Dimension(150, 30));

        buttonAdicionar_Vendedor.setBackground(new java.awt.Color(204, 255, 255));
        buttonAdicionar_Vendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconadd.png"))); // NOI18N
        buttonAdicionar_Vendedor.setPreferredSize(new java.awt.Dimension(100, 50));
        buttonAdicionar_Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionar_VendedorActionPerformed(evt);
            }
        });

        buttonExcluir_Vendedor.setBackground(new java.awt.Color(204, 255, 255));
        buttonExcluir_Vendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icondelete.png"))); // NOI18N
        buttonExcluir_Vendedor.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonExcluir_Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluir_VendedorActionPerformed(evt);
            }
        });

        buttonAlterar_Vendedor.setBackground(new java.awt.Color(204, 255, 255));
        buttonAlterar_Vendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconupdate.png"))); // NOI18N
        buttonAlterar_Vendedor.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonAlterar_Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterar_VendedorActionPerformed(evt);
            }
        });

        buttonPesquisar_Tabela_Vendedor.setBackground(new java.awt.Color(204, 255, 255));
        buttonPesquisar_Tabela_Vendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconsearch.png"))); // NOI18N
        buttonPesquisar_Tabela_Vendedor.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonPesquisar_Tabela_Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisar_Tabela_VendedorActionPerformed(evt);
            }
        });

        label_NUMEND_VEN.setText("Nº:");

        NUMEND_VEN.setPreferredSize(new java.awt.Dimension(100, 30));

        label_COMPEND_VEN.setText("Complemento: ");

        COMPEND_VEN.setPreferredSize(new java.awt.Dimension(100, 30));

        tableVendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "VENDEDOR", "EMAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVendedor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableVendedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableVendedorMouseClicked(evt);
            }
        });
        ScrollPane_Fornecedor.setViewportView(tableVendedor);

        javax.swing.GroupLayout painelVendedorLayout = new javax.swing.GroupLayout(painelVendedor);
        painelVendedor.setLayout(painelVendedorLayout);
        painelVendedorLayout.setHorizontalGroup(
            painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelVendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelVendedorLayout.createSequentialGroup()
                        .addGroup(painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelVendedorLayout.createSequentialGroup()
                                .addComponent(label_COMPEND_VEN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(COMPEND_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelVendedorLayout.createSequentialGroup()
                                .addGroup(painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_END_VEN)
                                    .addComponent(label_CID_CLI)
                                    .addComponent(label_EMAIL_VEN))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EMAIL_VEN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(END_VEN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CID_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelVendedorLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(label_DDDTEL_VEN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DDDTEL_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label_TEL_VEN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TEL_VEN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelVendedorLayout.createSequentialGroup()
                                .addComponent(label_UF_VEN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UF_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_CEP_VEN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CEP_VEN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelVendedorLayout.createSequentialGroup()
                                .addGap(0, 10, Short.MAX_VALUE)
                                .addGroup(painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelVendedorLayout.createSequentialGroup()
                                        .addComponent(label_DTNASC_VEN)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DATNASC_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painelVendedorLayout.createSequentialGroup()
                                        .addComponent(label_NUMEND_VEN)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(NUMEND_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(label_BAI_VEN)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BAI_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painelVendedorLayout.createSequentialGroup()
                                        .addComponent(label_SEX_VEN)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SEX_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(15, 15, 15))
                    .addGroup(painelVendedorLayout.createSequentialGroup()
                        .addGroup(painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelVendedorLayout.createSequentialGroup()
                                .addComponent(buttonAdicionar_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonExcluir_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonAlterar_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonLimpar_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonPesquisar_Tabela_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelVendedorLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_NOME_VEN)
                                    .addComponent(label_CPF_VEN))
                                .addGap(18, 18, 18)
                                .addGroup(painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CPF_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NOME_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(ScrollPane_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelVendedorLayout.setVerticalGroup(
            painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelVendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_NOME_VEN)
                    .addComponent(NOME_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelVendedorLayout.createSequentialGroup()
                        .addGroup(painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_CPF_VEN)
                            .addComponent(CPF_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(END_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_END_VEN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_CID_CLI)
                            .addComponent(CID_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(COMPEND_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_COMPEND_VEN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EMAIL_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_EMAIL_VEN))
                        .addGap(25, 25, 25)
                        .addGroup(painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonAdicionar_Vendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonExcluir_Vendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAlterar_Vendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonPesquisar_Tabela_Vendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonLimpar_Vendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelVendedorLayout.createSequentialGroup()
                        .addGroup(painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DATNASC_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_DTNASC_VEN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_SEX_VEN)
                            .addComponent(SEX_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_NUMEND_VEN)
                            .addComponent(NUMEND_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_BAI_VEN)
                            .addComponent(BAI_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_UF_VEN)
                            .addComponent(UF_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CEP_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_CEP_VEN))
                        .addGap(11, 11, 11)
                        .addGroup(painelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_DDDTEL_VEN)
                            .addComponent(DDDTEL_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEL_VEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_TEL_VEN))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelVendedorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ScrollPane_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TabelaPaineis_ModuloVendedor.addTab("Vendedor", painelVendedor);

        painelHistoricoServico.setBackground(new java.awt.Color(255, 255, 255));
        painelHistoricoServico.setPreferredSize(new java.awt.Dimension(600, 200));

        label_HISSER_COD_NOTFIS.setText("Nota Fiscal: ");

        label_HISSER_COD_SER.setText("Serviço: ");

        buttonLimpar_HistoricoServico.setBackground(new java.awt.Color(204, 255, 255));
        buttonLimpar_HistoricoServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconclean.png"))); // NOI18N
        buttonLimpar_HistoricoServico.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonLimpar_HistoricoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimpar_HistoricoServicoActionPerformed(evt);
            }
        });

        DefaultTableModel modeloHistoricoServico = new DefaultTableModel();
        tableHistoricoServico.setModel(modeloHistoricoServico);
        modeloHistoricoServico.addColumn("Identificador");
        modeloHistoricoServico.addColumn("Serviço");
        modeloHistoricoServico.addColumn("Quantidade");
        modeloHistoricoServico.addColumn("Valor");
        modeloHistoricoServico.addColumn("Data");
        modeloHistoricoServico.addColumn("Vendedor");
        modeloHistoricoServico.addColumn("Descrição");
        tableHistoricoServico.getColumnModel().getColumn(0).setPreferredWidth(80);
        tableHistoricoServico.getColumnModel().getColumn(0).setResizable(false);

        tableHistoricoServico.getColumnModel().getColumn(1).setPreferredWidth(110);
        tableHistoricoServico.getColumnModel().getColumn(1).setResizable(false);

        tableHistoricoServico.getColumnModel().getColumn(2).setPreferredWidth(80);
        tableHistoricoServico.getColumnModel().getColumn(2).setResizable(false);

        tableHistoricoServico.getColumnModel().getColumn(3).setPreferredWidth(145);
        tableHistoricoServico.getColumnModel().getColumn(3).setResizable(false);

        tableHistoricoServico.getColumnModel().getColumn(4).setPreferredWidth(145);
        tableHistoricoServico.getColumnModel().getColumn(4).setResizable(false);

        tableHistoricoServico.getColumnModel().getColumn(5).setPreferredWidth(145);
        tableHistoricoServico.getColumnModel().getColumn(5).setResizable(false);

        tableHistoricoServico.getColumnModel().getColumn(6).setPreferredWidth(145);
        tableHistoricoServico.getColumnModel().getColumn(6).setResizable(false);

        tableHistoricoServico.setColumnSelectionAllowed(true);
        tableHistoricoServico.getTableHeader().setReorderingAllowed(false);
        tableHistoricoServico.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableHistoricoServico.setSelectionMode(0);
        ScrollPane_HistoricoServico.setViewportView(tableHistoricoServico);
        tableHistoricoServico.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        buttonAdicionar_HistoricoServico.setBackground(new java.awt.Color(204, 255, 255));
        buttonAdicionar_HistoricoServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconadd.png"))); // NOI18N
        buttonAdicionar_HistoricoServico.setPreferredSize(new java.awt.Dimension(100, 50));
        buttonAdicionar_HistoricoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionar_HistoricoServicoActionPerformed(evt);
            }
        });

        buttonExcluir_HistoricoServico.setBackground(new java.awt.Color(204, 255, 255));
        buttonExcluir_HistoricoServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icondelete.png"))); // NOI18N
        buttonExcluir_HistoricoServico.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonExcluir_HistoricoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluir_HistoricoServicoActionPerformed(evt);
            }
        });

        buttonAlterar_HistoricoServico.setBackground(new java.awt.Color(204, 255, 255));
        buttonAlterar_HistoricoServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconupdate.png"))); // NOI18N
        buttonAlterar_HistoricoServico.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonAlterar_HistoricoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterar_HistoricoServicoActionPerformed(evt);
            }
        });

        buttonPesquisar_Tabela_HistoricoServico.setBackground(new java.awt.Color(204, 255, 255));
        buttonPesquisar_Tabela_HistoricoServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconsearch.png"))); // NOI18N
        buttonPesquisar_Tabela_HistoricoServico.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonPesquisar_Tabela_HistoricoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisar_Tabela_HistoricoServicoActionPerformed(evt);
            }
        });

        label_PES_COD_HISSER.setText("Pesquisar por Identificador");

        buttonPesquisar_COD_HISSER.setBackground(new java.awt.Color(204, 255, 255));
        buttonPesquisar_COD_HISSER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/iconsearch.png"))); // NOI18N
        buttonPesquisar_COD_HISSER.setPreferredSize(new java.awt.Dimension(100, 30));
        buttonPesquisar_COD_HISSER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisar_COD_HISSERActionPerformed(evt);
            }
        });

        label_DES_HISSER.setText("Histórico do Serviço: ");

        DES_HISSER.setPreferredSize(new java.awt.Dimension(100, 30));

        controller.NotaFiscalDAO notaFiscalDAO = new controller.NotaFiscalDAO();
        notaFiscalDAO.ComboBoxNotaFiscal(HISSER_COD_NOTFIS);

        controller.ItemServicoDAO itemServicoDAO = new controller.ItemServicoDAO();
        itemServicoDAO.ComboBoxServiço(HISSER_DES_SER);

        controller.HistoricoServicoDAO historicoServicoDAO = new controller.HistoricoServicoDAO();
        historicoServicoDAO.ComboBoxHistoricoServico(PES_COD_HISSER);

        javax.swing.GroupLayout painelHistoricoServicoLayout = new javax.swing.GroupLayout(painelHistoricoServico);
        painelHistoricoServico.setLayout(painelHistoricoServicoLayout);
        painelHistoricoServicoLayout.setHorizontalGroup(
            painelHistoricoServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelHistoricoServicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelHistoricoServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelHistoricoServicoLayout.createSequentialGroup()
                        .addComponent(buttonAdicionar_HistoricoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonExcluir_HistoricoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAlterar_HistoricoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonLimpar_HistoricoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPesquisar_Tabela_HistoricoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelHistoricoServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_PES_COD_HISSER)
                            .addGroup(painelHistoricoServicoLayout.createSequentialGroup()
                                .addComponent(PES_COD_HISSER, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonPesquisar_COD_HISSER, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(painelHistoricoServicoLayout.createSequentialGroup()
                        .addGroup(painelHistoricoServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelHistoricoServicoLayout.createSequentialGroup()
                                .addComponent(label_HISSER_COD_NOTFIS)
                                .addGap(52, 52, 52)
                                .addComponent(HISSER_COD_NOTFIS, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelHistoricoServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(painelHistoricoServicoLayout.createSequentialGroup()
                                    .addComponent(label_HISSER_COD_SER)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(HISSER_DES_SER, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(painelHistoricoServicoLayout.createSequentialGroup()
                                    .addComponent(label_DES_HISSER)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(DES_HISSER, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(ScrollPane_HistoricoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelHistoricoServicoLayout.setVerticalGroup(
            painelHistoricoServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelHistoricoServicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelHistoricoServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelHistoricoServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelHistoricoServicoLayout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addGroup(painelHistoricoServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(HISSER_COD_NOTFIS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_HISSER_COD_NOTFIS))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(painelHistoricoServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label_HISSER_COD_SER)
                                .addComponent(HISSER_DES_SER, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(painelHistoricoServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DES_HISSER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_DES_HISSER))
                            .addGap(104, 104, 104)
                            .addGroup(painelHistoricoServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(buttonAdicionar_HistoricoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonExcluir_HistoricoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonAlterar_HistoricoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonPesquisar_Tabela_HistoricoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonLimpar_HistoricoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(ScrollPane_HistoricoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelHistoricoServicoLayout.createSequentialGroup()
                        .addComponent(label_PES_COD_HISSER)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PES_COD_HISSER, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonPesquisar_COD_HISSER, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabelaPaineis_ModuloVendedor.addTab("Histórico de Serviços", painelHistoricoServico);

        javax.swing.GroupLayout painelModuloVendedorLayout = new javax.swing.GroupLayout(painelModuloVendedor);
        painelModuloVendedor.setLayout(painelModuloVendedorLayout);
        painelModuloVendedorLayout.setHorizontalGroup(
            painelModuloVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelModuloVendedorLayout.createSequentialGroup()
                .addGroup(painelModuloVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelModuloVendedorLayout.createSequentialGroup()
                        .addComponent(imgModuloVendedor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelModuloVendedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TabelaPaineis_ModuloVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelModuloVendedorLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonHelp_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonVoltarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addContainerGap())
        );
        painelModuloVendedorLayout.setVerticalGroup(
            painelModuloVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelModuloVendedorLayout.createSequentialGroup()
                .addComponent(imgModuloVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabelaPaineis_ModuloVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelModuloVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonVoltarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonHelp_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelModuloVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelModuloVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarVendedorActionPerformed
    view.MenuPrincipal vMenuPrincipal = new view.MenuPrincipal();
    dispose();
    vMenuPrincipal.setVisible(true);
    }//GEN-LAST:event_buttonVoltarVendedorActionPerformed

    private void buttonPesquisar_Tabela_VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesquisar_Tabela_VendedorActionPerformed
    controller.VendedorDAO vendedorDAO = new controller.VendedorDAO();
    model.Vendedor mVendedor = new model.Vendedor();
    vendedorDAO.pesquisarTabela_Vendedor(this, mVendedor);
    }//GEN-LAST:event_buttonPesquisar_Tabela_VendedorActionPerformed

    private void buttonAlterar_VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterar_VendedorActionPerformed
    controller.VendedorDAO vendedorDAO = new controller.VendedorDAO();
    model.Vendedor mVendedor = new model.Vendedor();
    vendedorDAO.atualizarVendedor(this, mVendedor);
    }//GEN-LAST:event_buttonAlterar_VendedorActionPerformed

    private void buttonExcluir_VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluir_VendedorActionPerformed
    controller.VendedorDAO vendedorDAO = new controller.VendedorDAO();
    model.Vendedor mVendedor = new model.Vendedor();
    vendedorDAO.excluirVendedor(this, mVendedor);
    }//GEN-LAST:event_buttonExcluir_VendedorActionPerformed

    private void buttonAdicionar_VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionar_VendedorActionPerformed
    controller.VendedorDAO vendedorDAO = new controller.VendedorDAO();
    model.Vendedor mVendedor = new model.Vendedor();
    vendedorDAO.getVendedor(this, mVendedor);
    vendedorDAO.adicionarVendedor(this, mVendedor);
    }//GEN-LAST:event_buttonAdicionar_VendedorActionPerformed

    private void buttonLimpar_VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimpar_VendedorActionPerformed
    controller.VendedorDAO vendedorDAO = new controller.VendedorDAO();
    vendedorDAO.cleanVendedor(this);
    }//GEN-LAST:event_buttonLimpar_VendedorActionPerformed

    private void buttonLimpar_HistoricoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimpar_HistoricoServicoActionPerformed
    controller.HistoricoServicoDAO historicoServicoDAO = new controller.HistoricoServicoDAO();
    historicoServicoDAO.cleanHistoricoServico(this);
    }//GEN-LAST:event_buttonLimpar_HistoricoServicoActionPerformed

    private void buttonAdicionar_HistoricoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionar_HistoricoServicoActionPerformed
    controller.HistoricoServicoDAO historicoServicoDAO = new controller.HistoricoServicoDAO();
    model.HistoricoServico mHistoricoServico = new model.HistoricoServico();
    model.NotaFiscal mNotaFiscal = new model.NotaFiscal();
    model.Servico mServico = new model.Servico();
    historicoServicoDAO.getHistoricoServico(this, mHistoricoServico, mNotaFiscal, mServico);
    historicoServicoDAO.adicionarHistoricoServico(this, mHistoricoServico, mNotaFiscal, mServico);
    }//GEN-LAST:event_buttonAdicionar_HistoricoServicoActionPerformed

    private void buttonExcluir_HistoricoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluir_HistoricoServicoActionPerformed
    controller.HistoricoServicoDAO historicoServicoDAO = new controller.HistoricoServicoDAO();
    model.HistoricoServico mHistoricoServico = new model.HistoricoServico();
    model.NotaFiscal mNotaFiscal = new model.NotaFiscal();
    model.Servico mServico = new model.Servico();
    historicoServicoDAO.excluirHistoricoServico(this, mHistoricoServico, mNotaFiscal, mServico);
    }//GEN-LAST:event_buttonExcluir_HistoricoServicoActionPerformed

    private void buttonAlterar_HistoricoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterar_HistoricoServicoActionPerformed
    controller.HistoricoServicoDAO historicoServicoDAO = new controller.HistoricoServicoDAO();
    model.HistoricoServico mHistoricoServico = new model.HistoricoServico();
    model.NotaFiscal mNotaFiscal = new model.NotaFiscal();
    model.Servico mServico = new model.Servico();
    historicoServicoDAO.atualizarHistoricoServico(this, mHistoricoServico, mNotaFiscal, mServico);
    }//GEN-LAST:event_buttonAlterar_HistoricoServicoActionPerformed

    private void buttonPesquisar_Tabela_HistoricoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesquisar_Tabela_HistoricoServicoActionPerformed
    controller.HistoricoServicoDAO historicoServicoDAO = new controller.HistoricoServicoDAO();
    model.HistoricoServico mHistoricoServico = new model.HistoricoServico();
    model.NotaFiscal mNotaFiscal = new model.NotaFiscal();
    model.Servico mServico = new model.Servico();
    historicoServicoDAO.pesquisarTabela_HistoricoServico(this, mHistoricoServico, mNotaFiscal, mServico);
    }//GEN-LAST:event_buttonPesquisar_Tabela_HistoricoServicoActionPerformed

    private void buttonPesquisar_COD_HISSERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesquisar_COD_HISSERActionPerformed
    controller.HistoricoServicoDAO historicoServicoDAO = new controller.HistoricoServicoDAO();
    model.HistoricoServico mHistoricoServico = new model.HistoricoServico();
    model.NotaFiscal mNotaFiscal = new model.NotaFiscal();
    model.Servico mServico = new model.Servico();
    historicoServicoDAO.pesquisarHistoricoServico(this, mHistoricoServico, mNotaFiscal, mServico);
    }//GEN-LAST:event_buttonPesquisar_COD_HISSERActionPerformed

    private void tableVendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVendedorMouseClicked
        controller.VendedorDAO vendedorDAO = new controller.VendedorDAO();
        model.Vendedor mVendedor = new model.Vendedor();
        vendedorDAO.pesquisarVendedor(this, mVendedor, "sim");
    }//GEN-LAST:event_tableVendedorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            getLogger(ModuloVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
            new ModuloVendedor().setVisible(true);
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField BAI_VEN;
    public javax.swing.JTextField CEP_VEN;
    public javax.swing.JTextField CID_VEN;
    public javax.swing.JTextField COMPEND_VEN;
    public javax.swing.JTextField CPF_VEN;
    public javax.swing.JTextField DATNASC_VEN;
    public javax.swing.JTextField DDDTEL_VEN;
    public javax.swing.JTextField DES_HISSER;
    public javax.swing.JTextField EMAIL_VEN;
    public javax.swing.JTextField END_VEN;
    public javax.swing.JComboBox HISSER_COD_NOTFIS;
    public javax.swing.JComboBox HISSER_DES_SER;
    public javax.swing.JTextField NOME_VEN;
    public javax.swing.JTextField NUMEND_VEN;
    public javax.swing.JComboBox PES_COD_HISSER;
    public javax.swing.JComboBox SEX_VEN;
    private javax.swing.JScrollPane ScrollPane_Fornecedor;
    private javax.swing.JScrollPane ScrollPane_HistoricoServico;
    public javax.swing.JTextField TEL_VEN;
    public javax.swing.JTabbedPane TabelaPaineis_ModuloVendedor;
    public javax.swing.JComboBox UF_VEN;
    private javax.swing.JButton buttonAdicionar_HistoricoServico;
    private javax.swing.JButton buttonAdicionar_Vendedor;
    private javax.swing.JButton buttonAlterar_HistoricoServico;
    private javax.swing.JButton buttonAlterar_Vendedor;
    private javax.swing.JButton buttonExcluir_HistoricoServico;
    private javax.swing.JButton buttonExcluir_Vendedor;
    private javax.swing.JButton buttonHelp_Vendedor;
    private javax.swing.JButton buttonLimpar_HistoricoServico;
    private javax.swing.JButton buttonLimpar_Vendedor;
    private javax.swing.JButton buttonPesquisar_COD_HISSER;
    private javax.swing.JButton buttonPesquisar_Tabela_HistoricoServico;
    private javax.swing.JButton buttonPesquisar_Tabela_Vendedor;
    private javax.swing.JButton buttonVoltarVendedor;
    private javax.swing.JLabel imgModuloVendedor;
    private javax.swing.JLabel label_BAI_VEN;
    private javax.swing.JLabel label_CEP_VEN;
    private javax.swing.JLabel label_CID_CLI;
    private javax.swing.JLabel label_COMPEND_VEN;
    private javax.swing.JLabel label_CPF_VEN;
    private javax.swing.JLabel label_DDDTEL_VEN;
    private javax.swing.JLabel label_DES_HISSER;
    private javax.swing.JLabel label_DTNASC_VEN;
    private javax.swing.JLabel label_EMAIL_VEN;
    private javax.swing.JLabel label_END_VEN;
    private javax.swing.JLabel label_HISSER_COD_NOTFIS;
    private javax.swing.JLabel label_HISSER_COD_SER;
    private javax.swing.JLabel label_NOME_VEN;
    private javax.swing.JLabel label_NUMEND_VEN;
    private javax.swing.JLabel label_PES_COD_HISSER;
    private javax.swing.JLabel label_SEX_VEN;
    private javax.swing.JLabel label_TEL_VEN;
    private javax.swing.JLabel label_UF_VEN;
    public javax.swing.JPanel painelHistoricoServico;
    private javax.swing.JPanel painelModuloVendedor;
    public javax.swing.JPanel painelVendedor;
    public javax.swing.JTable tableHistoricoServico;
    public javax.swing.JTable tableVendedor;
    // End of variables declaration//GEN-END:variables
    private static final Logger LOG = getLogger(ModuloVendedor.class.getName());
}
